import type { Lang } from "./i18n";

export function getPricingCopy(lang: Lang) {
  return {
    businessName:
      {
        no: "Bedrift",
        en: "Business",
        sv: "Företag",
        da: "Erhverv",
        fi: "Yritys",
        de: "Business",
        nl: "Zakelijk",
        fr: "Entreprise",
        pl: "Biznes",
        es: "Empresa",
        it: "Business",
        pt: "Empresas",
      }[lang] ?? "Business",
    businessDesc:
      {
        no: "300 beregninger per måned",
        en: "300 estimates per month",
        sv: "300 beräkningar per månad",
        da: "300 beregninger pr. måned",
        fi: "300 arviota kuukaudessa",
        de: "300 Schätzungen pro Monat",
        nl: "300 schattingen per maand",
        fr: "300 estimations par mois",
        pl: "300 wycen miesięcznie",
        es: "300 estimaciones al mes",
        it: "300 stime al mese",
        pt: "300 estimativas por mês",
      }[lang] ?? "300 estimates per month",
    businessFeatures: {
      no: ["Alle basisfunksjoner", "Egen logo og farger", "Pris per m³ og tilbud", "PDF-rapport"],
      en: ["All core features", "Your logo and colours", "Rate per m³ and quotes", "PDF report"],
      sv: [
        "Alla kärnfunktioner",
        "Egen logotyp och egna färger",
        "Pris per m³ och offerter",
        "PDF-rapport",
      ],
      da: [
        "Alle kernefunktioner",
        "Eget logo og egne farver",
        "Pris pr. m³ og tilbud",
        "PDF-rapport",
      ],
      fi: [
        "Kaikki perusominaisuudet",
        "Oma logo ja omat värit",
        "Hinta per m³ ja tarjoukset",
        "PDF-raportti",
      ],
      de: [
        "Alle Kernfunktionen",
        "Eigenes Logo und eigene Farben",
        "Preis pro m³ und Angebote",
        "PDF-Bericht",
      ],
      nl: [
        "Alle basisfuncties",
        "Je eigen logo en kleuren",
        "Prijs per m³ en offertes",
        "PDF-rapport",
      ],
      fr: [
        "Toutes les fonctions essentielles",
        "Votre logo et vos couleurs",
        "Tarif au m³ et devis",
        "Rapport PDF",
      ],
      pl: [
        "Wszystkie funkcje podstawowe",
        "Własne logo i kolory",
        "Cena za m³ i oferty",
        "Raport PDF",
      ],
      es: [
        "Todas las funciones principales",
        "Tu logotipo y tus colores",
        "Tarifa por m³ y presupuestos",
        "Informe PDF",
      ],
      it: [
        "Tutte le funzioni essenziali",
        "Logo e colori del tuo marchio",
        "Tariffa per m³ e preventivi",
        "Report PDF",
      ],
      pt: [
        "Todas as funcionalidades essenciais",
        "O seu logótipo e as suas cores",
        "Preço por m³ e orçamentos",
        "Relatório PDF",
      ],
    }[lang] ?? [
      "All core features",
      "Your logo and colours",
      "Rate per m³ and quotes",
      "PDF report",
    ],
    enterprisePrice:
      {
        no: "Kontakt oss",
        en: "Talk to us",
        sv: "Prata med oss",
        da: "Tal med os",
        fi: "Ota yhteyttä",
        de: "Sprechen Sie mit uns",
        nl: "Neem contact op",
        fr: "Parlons-en",
        pl: "Porozmawiaj z nami",
        es: "Hablemos",
        it: "Parliamone",
        pt: "Fale connosco",
      }[lang] ?? "Talk to us",
    enterpriseDesc:
      {
        no: "Ubegrenset volum",
        en: "Unlimited volume",
        sv: "Obegränsad volym",
        da: "Ubegrænset volumen",
        fi: "Rajaton määrä arvioita",
        de: "Unbegrenztes Volumen",
        nl: "Onbeperkt volume",
        fr: "Volume illimité",
        pl: "Nielimitowana liczba wycen",
        es: "Volumen ilimitado",
        it: "Volume illimitato",
        pt: "Volume ilimitado",
      }[lang] ?? "Unlimited volume",
    enterpriseName:
      {
        no: "Enterprise",
        en: "Enterprise",
        sv: "Enterprise",
        da: "Enterprise",
        fi: "Enterprise",
        de: "Enterprise",
        nl: "Enterprise",
        fr: "Enterprise",
        pl: "Enterprise",
        es: "Enterprise",
        it: "Enterprise",
        pt: "Enterprise",
      }[lang] ?? "Enterprise",
    enterpriseFeatures: {
      no: ["Alt i Bedrift", "Flere avdelinger", "API og integrasjoner", "Egen kundekontakt"],
      en: [
        "Everything in Business",
        "Multiple branches",
        "API and integrations",
        "Dedicated contact",
      ],
      sv: ["Allt i Företag", "Flera kontor", "API och integrationer", "Egen kontaktperson"],
      da: ["Alt i Erhverv", "Flere afdelinger", "API og integrationer", "Fast kontaktperson"],
      fi: [
        "Kaikki Yritys-paketista",
        "Useita toimipisteitä",
        "API ja integraatiot",
        "Oma yhteyshenkilö",
      ],
      de: [
        "Alles aus Business",
        "Mehrere Standorte",
        "API und Integrationen",
        "Persönliche Ansprechperson",
      ],
      nl: [
        "Alles uit Zakelijk",
        "Meerdere vestigingen",
        "API en integraties",
        "Vaste contactpersoon",
      ],
      fr: [
        "Tout ce qui est inclus dans Entreprise",
        "Plusieurs agences",
        "API et intégrations",
        "Interlocuteur dédié",
      ],
      pl: [
        "Wszystko z pakietu Biznes",
        "Wiele oddziałów",
        "API i integracje",
        "Dedykowany opiekun",
      ],
      es: [
        "Todo lo de Empresa",
        "Varias sucursales",
        "API e integraciones",
        "Persona de contacto dedicada",
      ],
      it: [
        "Tutto ciò che è incluso in Business",
        "Più sedi",
        "API e integrazioni",
        "Referente dedicato",
      ],
      pt: [
        "Tudo o que está no plano Empresas",
        "Várias filiais",
        "API e integrações",
        "Contacto dedicado",
      ],
    }[lang] ?? [
      "Everything in Business",
      "Multiple branches",
      "API and integrations",
      "Dedicated contact",
    ],
    singleName:
      {
        no: "Én beregning",
        en: "Single estimate",
        sv: "1 beräkning",
        da: "1 beregning",
        fi: "1 arvio",
        de: "1 Schätzung",
        nl: "1 schatting",
        fr: "1 estimation",
        pl: "1 wycena",
        es: "1 estimación",
        it: "1 stima",
        pt: "1 estimativa",
      }[lang] ?? "Single estimate",
    singleDesc:
      {
        no: "For én flytting",
        en: "For one move",
        sv: "För en flytt",
        da: "Til én flytning",
        fi: "Yhtä muuttoa varten",
        de: "Für einen Umzug",
        nl: "Voor één verhuizing",
        fr: "Pour un déménagement",
        pl: "Na jedną przeprowadzkę",
        es: "Para una mudanza",
        it: "Per un trasloco",
        pt: "Para uma mudança",
      }[lang] ?? "For one move",
    singleFeatures: {
      no: ["Romvideo + sjekkliste", "Romvis sortering", "PDF-rapport"],
      en: ["Room video + checklist", "Room grouping", "PDF report"],
      sv: ["Rumsvideo + checklista", "Sortering per rum", "PDF-rapport"],
      da: ["Rumvideo + tjekliste", "Sortering pr. rum", "PDF-rapport"],
      fi: ["Huonevideo + tarkistuslista", "Ryhmittely huoneittain", "PDF-raportti"],
      de: ["Raumvideo + Checkliste", "Sortierung nach Räumen", "PDF-Bericht"],
      nl: ["Kamervideo + checklist", "Groepering per kamer", "PDF-rapport"],
      fr: ["Vidéo de pièce + checklist", "Classement par pièce", "Rapport PDF"],
      pl: ["Nagranie pokoju + lista kontrolna", "Podział na pokoje", "Raport PDF"],
      es: ["Vídeo de la estancia + lista", "Agrupación por estancia", "Informe PDF"],
      it: ["Video della stanza + checklist", "Raggruppamento per stanza", "Report PDF"],
      pt: ["Vídeo da divisão + checklist", "Agrupamento por divisão", "Relatório PDF"],
    }[lang] ?? ["Room video + checklist", "Room grouping", "PDF report"],
    bundleName:
      {
        no: "3 beregninger",
        en: "3 estimates",
        sv: "3 beräkningar",
        da: "3 beregninger",
        fi: "3 arviota",
        de: "3 Schätzungen",
        nl: "3 schattingen",
        fr: "3 estimations",
        pl: "3 wyceny",
        es: "3 estimaciones",
        it: "3 stime",
        pt: "3 estimativas",
      }[lang] ?? "3 estimates",
    bundleDesc:
      {
        no: "Spar 88 NOK",
        en: "Save 88 NOK",
        sv: "Spara 88 NOK",
        da: "Spar 88 NOK",
        fi: "Säästä 88 NOK",
        de: "88 NOK sparen",
        nl: "Bespaar 88 NOK",
        fr: "Économisez 88 NOK",
        pl: "Oszczędź 88 NOK",
        es: "Ahorra 88 NOK",
        it: "Risparmia 88 NOK",
        pt: "Poupe 88 NOK",
      }[lang] ?? "Save 88 NOK",
    bundleFeatures: {
      no: ["3 komplette beregninger", "Romvideo + sjekkliste", "PDF-rapporter"],
      en: ["3 complete estimates", "Room video + checklist", "PDF reports"],
      sv: ["3 kompletta beräkningar", "Rumsvideo + checklista", "PDF-rapporter"],
      da: ["3 komplette beregninger", "Rumvideo + tjekliste", "PDF-rapporter"],
      fi: ["3 valmista arviota", "Huonevideo + tarkistuslista", "PDF-raportit"],
      de: ["3 vollständige Schätzungen", "Raumvideo + Checkliste", "PDF-Berichte"],
      nl: ["3 complete schattingen", "Kamervideo + checklist", "PDF-rapporten"],
      fr: ["3 estimations complètes", "Vidéo de pièce + checklist", "Rapports PDF"],
      pl: ["3 pełne wyceny", "Nagranie pokoju + lista kontrolna", "Raporty PDF"],
      es: ["3 estimaciones completas", "Vídeo de la estancia + lista", "Informes PDF"],
      it: ["3 stime complete", "Video della stanza + checklist", "Report PDF"],
      pt: ["3 estimativas completas", "Vídeo da divisão + checklist", "Relatórios PDF"],
    }[lang] ?? ["3 complete estimates", "Room video + checklist", "PDF reports"],
  };
}
