// Polish labels for the estimate report. Used when the report language is set
// to Polish; anything missing falls back to the English wording.
export const reportPl: Record<string, string> = {
  "res.title": "Wycena objętości",
  "res.total": "Objętość całkowita",
  "res.items": "przedmiotów",
  "res.item": "Przedmiot",
  "res.dims": "Wymiary (cm)",
  "res.qty": "Ilość",
  "res.volume": "Objętość",
  "res.confidence": "pewności",
  "res.pdf": "Pobierz PDF",
  "res.share": "Kopiuj link do udostępnienia",
  "res.copied": "Link skopiowany",
  "res.photos": "Zdjęcia",
  "res.room": "Pokój",
  "res.renameRoom": "Zmień nazwę pokoju",
  "res.moveRoom": "Przenieś do pokoju",
  "res.roomTotal": "Objętość pokoju",
  "res.other": "Inne",
  "res.notFound": "Nie znaleziono wyceny.",
  "res.estimated": "Szacowana cena",
  "res.disclaimer":
    "Wycena opiera się na zdjęciach i ma charakter orientacyjny do czasu zatwierdzenia przez firmę przeprowadzkową.",

  "rep.status.draft": "Szkic",
  "rep.status.ready": "Gotowe do udostępnienia",
  "rep.status.processed": "Przetworzone",
  "rep.estimateId": "Numer wyceny",
  "rep.netVolume": "Obliczona objętość netto",
  "rep.recommended": "Zalecany pojazd/miejsce (wraz z zapasem +25%)",
  "rep.counts": "Łączna liczba przedmiotów i pokoi",
  "rep.itemsWord": "przedmiotów",
  "rep.roomsWord": "pokoi",
  "rep.shareSecret": "Udostępnij tajny link",
  "rep.pdf": "Pobierz raport PDF",
  "rep.requestQuote": "Poproś o niezobowiązującą ofertę",
  "rep.truck.van": "Mały bus (kat. B)",
  "rep.truck.small": "Duży bus / mała ciężarówka",
  "rep.truck.medium": "Ciężarówka 3,5–7,5 t",
  "rep.truck.large": "Duża ciężarówka / naczepa",
  "rep.storage": "Odpowiada magazynowi o powierzchni ok.",

  "rep.included": "Do przewiezienia",
  "rep.excluded": "Zostaje / do utylizacji",
  "rep.tag.disassemble": "Do demontażu",
  "rep.tag.fragile": "Bardzo delikatne",
  "rep.tag.heavy": "Ciężkie / wymaga 2 osób",
  "rep.tag.discard": "Do wyrzucenia/oddania",
  "rep.addNote": "Dodaj uwagę …",
  "rep.itemDeleted": "Przedmiot usunięty",
  "rep.undo": "Cofnij",
  "rep.rename": "Zmień nazwę",

  "rep.accessTitle": "Dostęp i warunki",
  "rep.floor": "Piętro",
  "rep.elevator": "Jest winda (mieści standardowe meble)",
  "rep.carry": "Odległość noszenia",
  "rep.carryHelp": "Metry od drzwi wejściowych do miejsca parkowania",
  "rep.generalNotes": "Szczególne uwagi do zlecenia",
  "rep.generalNotesPh": "Np. wąska klatka schodowa, fortepian trzeba nieść",
  "rep.saveAccess": "Zapisz dane dostępu",
  "rep.saved": "Zapisano",

  "rep.viewCustomer": "Widok klienta",
  "rep.viewBusiness": "Widok firmy",
  "rep.internalTitle": "Kalkulacja wewnętrzna i notatki",
  "rep.hourly": "Stawka godzinowa",
  "rep.hours": "Szacowane godziny",
  "rep.fixed": "Cena stała (objętość × stawka za m³)",
  "rep.internalNotes": "Notatki wewnętrzne",
  "rep.checklist": "Lista kontrolna zlecenia",
  "rep.check1": "Potwierdzono dostęp i odległość noszenia",
  "rep.check2": "Wyjaśniono demontaż",
  "rep.check3": "Oznaczono delikatne przedmioty",
  "rep.check4": "Zarezerwowano pojazd",
  "rep.export": "Eksportuj",

  "rep.reportLang": "Język raportu",
  "rep.reportLangHelp":
    "Wybierz język, w którym raport jest wyświetlany, udostępniany i zapisywany. Twoje zmiany pozostają bez zmian.",
  "rep.tender": "Tryb przetargowy – ukryj ceny",
  "rep.tenderHelp": "Ukrywa szacowaną cenę i wszystkie kalkulacje w raporcie, PDF i udostępnionym linku.",

  "rep.storageTitle": "Magazynowanie tymczasowe",
  "rep.storageEnabled": "Rzeczy trafiają do magazynu",
  "rep.storageCompany": "Nazwa firmy magazynowej",
  "rep.storageAddress": "Pełny adres",
  "rep.storageContact": "Osoba kontaktowa",
  "rep.storagePhone": "Telefon",

  "rep.deliveryTitle": "Dostawa do nowego mieszkania",
  "rep.deliveryAddress": "Pełny adres",
  "rep.deliveryFloor": "Piętro",
  "rep.deliveryElevator": "Winda w budynku",
  "rep.deliveryCarry": "Odległość noszenia (metry)",
  "rep.deliveryNotes": "Uwagi dotyczące dostawy",

  "rep.packingTitle": "Pakowanie i materiały",
  "rep.packingRequested": "Chcemy pomoc przy pakowaniu",
  "rep.packingLevel": "Zakres",
  "rep.packingLevel.fragile": "Tylko delikatne przedmioty",
  "rep.packingLevel.partial": "Pakowanie częściowe",
  "rep.packingLevel.full": "Pełne pakowanie",
  "rep.materials": "Potrzebne materiały",
  "mat.boxes": "Kartony",
  "mat.bubble": "Folia bąbelkowa (rolki)",
  "mat.paper": "Papier pakowy (paczki)",
  "mat.tape": "Taśma (rolki)",
  "mat.wardrobe": "Kartony na garderobę",
  "mat.mattress": "Pokrowce na materace",
  "mat.blanket": "Koce meblowe",
  "rep.packingNotes": "Przedmioty specjalne (sztuka, fortepian, TV)",
  "rep.saveExtras": "Zapisz logistykę",

  "dash.approve": "Zatwierdź",
  "dash.approved": "Zatwierdzone",
  "dash.saveItem": "Zapisz",
  "dash.deleteItem": "Usuń",
  "upload.failed": "Coś poszło nie tak. Spróbuj ponownie.",

  "share.title": "Udostępnij wycenę",
  "share.sub": "Wyślij raport wybranym kanałem.",
  "share.whatsapp": "Udostępnij na WhatsApp",
  "share.facebook": "Udostępnij na Facebooku",
  "share.linkedin": "Udostępnij na LinkedIn",
  "share.x": "Udostępnij na X",
  "share.email": "Udostępnij e-mailem",
  "share.more": "Więcej",
};

export type ReportLang = "no" | "en" | "pl";
