// Auto-generated report translations. English is the source of truth.
export const reportLangs: Record<string, Record<string, string>> = {
  "sv": {
    "dash.approve": "Godkänn",
    "dash.approved": "Godkänd",
    "dash.claim": "Tilldela mitt företag",
    "dash.deleteItem": "Radera",
    "dash.saveItem": "Spara",
    "rep.accessTitle": "Tillgång & förhållanden",
    "rep.addNote": "Lägg till en anteckning…",
    "rep.carry": "Bärsträcka",
    "rep.carryHelp": "Meter från ytterdörr till parkeringsplats för lastbil",
    "rep.check1": "Tillgång och bärsträcka bekräftad",
    "rep.check2": "Demontering klargjord",
    "rep.check3": "Ömtåliga föremål markerade",
    "rep.check4": "Fordonets storlek bokad",
    "rep.checklist": "Operativ checklista",
    "rep.claimHelp": "Denna offert tillhör ännu inget företag. Tilldela den för att redigera och följa upp den.",
    "rep.counts": "Totalt antal föremål & rum",
    "rep.deliveryAddress": "Fullständig adress",
    "rep.deliveryCarry": "Bärsträcka (meter)",
    "rep.deliveryElevator": "Hiss i byggnaden",
    "rep.deliveryFloor": "Våning",
    "rep.deliveryNotes": "Leveransanteckningar",
    "rep.deliveryTitle": "Leverans till det nya hemmet",
    "rep.elevator": "Har hiss (passar standardmöbler)",
    "rep.estimateId": "Offert-ID",
    "rep.excluded": "Behålls / kastas",
    "rep.export": "Exportera",
    "rep.fixed": "Fast pris (volym × pris per m³)",
    "rep.floor": "Våning",
    "rep.generalNotes": "Särskilda anteckningar för uppdraget",
    "rep.generalNotesPh": "T.ex. tullväg, smal trappa, piano måste bäras",
    "rep.hourly": "Timpris",
    "rep.hours": "Beräknade timmar",
    "rep.included": "Ska flyttas",
    "rep.internalNotes": "Interna anteckningar",
    "rep.internalTitle": "Intern beräkning & anteckningar",
    "rep.itemDeleted": "Föremål raderat",
    "rep.itemsWord": "föremål",
    "rep.materials": "Packmaterial som behövs",
    "rep.netVolume": "Beräknad nettovolym",
    "rep.packingLevel": "Omfattning",
    "rep.packingLevel.fragile": "Endast ömtåliga föremål",
    "rep.packingLevel.full": "Fullständig packning",
    "rep.packingLevel.partial": "Delvis packning",
    "rep.packingNotes": "Särskilda föremål (konst, piano, TV)",
    "rep.packingRequested": "Vi önskar hjälp med packning",
    "rep.packingTitle": "Packning och material",
    "rep.pdf": "Ladda ner PDF-rapport",
    "rep.recommended": "Rekommenderat fordon/utrymme (inkl. stuvningsfaktor +25%)",
    "rep.rename": "Byt namn",
    "rep.reportLang": "Rapportspråk",
    "rep.reportLangHelp": "Välj vilket språk rapporten visas, delas och sparas på. Dina egna ändringar behålls.",
    "rep.requestQuote": "Begär en kostnadsfri offert",
    "rep.roomsWord": "rum",
    "rep.saveAccess": "Spara åtkomstuppgifter",
    "rep.saveExtras": "Spara logistik",
    "rep.saved": "Sparat",
    "rep.shareSecret": "Dela hemlig länk",
    "rep.status.draft": "Utkast",
    "rep.status.processed": "Bearbetad",
    "rep.status.ready": "Redo att delas",
    "rep.storage": "Ungefär en förvaringsenhet på ca",
    "rep.storageAddress": "Fullständig adress",
    "rep.storageCompany": "Magasineringsföretag",
    "rep.storageContact": "Kontaktperson",
    "rep.storageEnabled": "Föremål går till mellanlagring",
    "rep.storagePhone": "Telefon",
    "rep.storageTitle": "Mellanlagring / Eget förråd",
    "rep.tag.disassemble": "Behöver demonteras",
    "rep.tag.discard": "Kastas / skänks bort",
    "rep.tag.fragile": "Extra ömtålig",
    "rep.tag.heavy": "Tung / kräver 2 personer",
    "rep.tender": "Anbudsläge – dölj priser",
    "rep.tenderHelp": "Döljer det beräknade priset och alla prisberäkningar i rapporten, PDF:en och den delade länken.",
    "rep.truck.large": "Stor flyttlastbil / släp",
    "rep.truck.medium": "Flyttlastbil 3.5–7.5 t",
    "rep.truck.small": "Stor skåpbil / liten flyttbil",
    "rep.truck.van": "Liten skåpbil (klass B)",
    "rep.undo": "Ångra",
    "rep.viewBusiness": "Företagsvy",
    "rep.viewCustomer": "Kundvy",
    "res.confidence": "Förtroende",
    "res.copied": "Länk kopierad",
    "res.dims": "Mått (cm)",
    "res.disclaimer": "Denna offert baseras på video av rummet och en användarverifierad checklista, och är vägledande tills flyttfirman godkänner den.",
    "res.estimated": "Beräknat pris",
    "res.item": "Föremål",
    "res.items": "föremål",
    "res.moveRoom": "Flytta till rum",
    "res.notFound": "Offert hittades inte.",
    "res.other": "Övrigt",
    "res.pdf": "Ladda ner PDF",
    "res.photos": "Foton",
    "res.qty": "Antal",
    "res.renameRoom": "Byt namn på rum",
    "res.room": "Rum",
    "res.roomTotal": "Rumsvolym",
    "res.share": "Kopiera delningslänk",
    "res.title": "Volymberäkning",
    "res.total": "Total volym",
    "res.volume": "Volym",
    "upload.failed": "Något gick fel. Vänligen försök igen."
  },
  "da": {
    "dash.approve": "Godkend",
    "dash.approved": "Godkendt",
    "dash.claim": "Tilmeld min virksomhed",
    "dash.deleteItem": "Slet",
    "dash.saveItem": "Gem",
    "rep.accessTitle": "Adgang & forhold",
    "rep.addNote": "Tilføj en note …",
    "rep.carry": "Bærevej",
    "rep.carryHelp": "Meter fra hoveddør til lastbilparkering",
    "rep.check1": "Adgangsforhold og bærevej bekræftet",
    "rep.check2": "Afmontering afklaret",
    "rep.check3": "Sarmerlige genstande markeret",
    "rep.check4": "Køretøjsstørrelse booket",
    "rep.checklist": "Tjekliste for udførelse",
    "rep.claimHelp": "Dette estimat tilhører endnu ikke en virksomhed. Tilmeld det for at redigere og følge op.",
    "rep.counts": "Antal genstande & rum",
    "rep.deliveryAddress": "Fuld adresse",
    "rep.deliveryCarry": "Bærevej (meter)",
    "rep.deliveryElevator": "Elevator i bygningen",
    "rep.deliveryFloor": "Etage",
    "rep.deliveryNotes": "Leveringsnoter",
    "rep.deliveryTitle": "Levering til det nye hjem",
    "rep.elevator": "Har elevator (passer til standardmøbler)",
    "rep.estimateId": "Estimat-ID",
    "rep.excluded": "Bliver / Kasseres",
    "rep.export": "Eksporter",
    "rep.fixed": "Fast pris (volumen × pris pr. m³)",
    "rep.floor": "Etage",
    "rep.generalNotes": "Særlige bemærkninger til opgaven",
    "rep.generalNotesPh": "F.eks. betalingsvej, smal trappeopgang, klaver skal bæres",
    "rep.hourly": "Timepris",
    "rep.hours": "Estimeret antal timer",
    "rep.included": "Skal flyttes",
    "rep.internalNotes": "Interne noter",
    "rep.internalTitle": "Intern beregning & noter",
    "rep.itemDeleted": "Genstand slettet",
    "rep.itemsWord": "genstande",
    "rep.materials": "Nødvendige pakkematerialer",
    "rep.netVolume": "Beregnet nettovolumen",
    "rep.packingLevel": "Omfang",
    "rep.packingLevel.fragile": "Kun skrøbelige genstande",
    "rep.packingLevel.full": "Fuld pakning",
    "rep.packingLevel.partial": "Delvis pakning",
    "rep.packingNotes": "Særlige genstande (kunst, klaver, TV)",
    "rep.packingRequested": "Vi ønsker hjælp til pakning",
    "rep.packingTitle": "Pakning og materialer",
    "rep.pdf": "Download PDF-rapport",
    "rep.recommended": "Anbefalet køretøj/plads (inkl. stuvningsfaktor +25%)",
    "rep.rename": "Omdøb",
    "rep.reportLang": "Rapportsprog",
    "rep.reportLangHelp": "Vælg det sprog rapporten vises, deles og gemmes på. Dine egne redigeringer bevares.",
    "rep.requestQuote": "Anmod om et uforpligtende tilbud",
    "rep.roomsWord": "rum",
    "rep.saveAccess": "Gem adgangsoplysninger",
    "rep.saveExtras": "Gem logistik",
    "rep.saved": "Gemt",
    "rep.shareSecret": "Del hemmeligt link",
    "rep.status.draft": "Udkast",
    "rep.status.processed": "Behandlet",
    "rep.status.ready": "Klar til deling",
    "rep.storage": "Ca. et opbevaringsrum på ca.",
    "rep.storageAddress": "Fuld adresse",
    "rep.storageCompany": "Opbevaringsfirma",
    "rep.storageContact": "Kontaktperson",
    "rep.storageEnabled": "Genstande går til midlertidig opbevaring",
    "rep.storagePhone": "Telefon",
    "rep.storageTitle": "Midlertidig opbevaring / self-storage",
    "rep.tag.disassemble": "Skal skilles ad",
    "rep.tag.discard": "Kassér / gives væk",
    "rep.tag.fragile": "Ekstra skrøbelig",
    "rep.tag.heavy": "Tung / kræver 2 personer",
    "rep.tender": "Tilstandsbud – skjul priser",
    "rep.tenderHelp": "Skjuler den estimerede pris og alle prisberegninger i rapporten, PDF'en og det delte link.",
    "rep.truck.large": "Stor flyttebil / trailer",
    "rep.truck.medium": "Flyttebil 3.5–7.5 t",
    "rep.truck.small": "Stor varevogn / lille flyttebil",
    "rep.truck.van": "Lille varevogn (klasse B)",
    "rep.undo": "Fortryd",
    "rep.viewBusiness": "Virksomhedsvisning",
    "rep.viewCustomer": "Kundevisning",
    "res.confidence": "Sikkerhed",
    "res.copied": "Link kopieret",
    "res.dims": "Mål (cm)",
    "res.disclaimer": "Dette estimat er baseret på rumvideo og en brugerbekræftet tjekliste, og er vejledende indtil flyttefirmaet godkender det.",
    "res.estimated": "Estimeret pris",
    "res.item": "Genstand",
    "res.items": "genstande",
    "res.moveRoom": "Flyt til rum",
    "res.notFound": "Estimat ikke fundet.",
    "res.other": "Andet",
    "res.pdf": "Download PDF",
    "res.photos": "Billeder",
    "res.qty": "Antal",
    "res.renameRoom": "Omdøb rum",
    "res.room": "Rum",
    "res.roomTotal": "Rumvolumen",
    "res.share": "Kopier delelink",
    "res.title": "Volumenestimat",
    "res.total": "Samlet volumen",
    "res.volume": "Volumen",
    "upload.failed": "Noget gik galt. Prøv venligst igen."
  },
  "fi": {
    "dash.approve": "Hyväksy",
    "dash.approved": "Hyväksytty",
    "dash.claim": "Lunasta yritykselleni",
    "dash.deleteItem": "Poista",
    "dash.saveItem": "Tallenna",
    "rep.accessTitle": "Kulku & olosuhteet",
    "rep.addNote": "Lisää huomautus…",
    "rep.carry": "Kantomatka",
    "rep.carryHelp": "Metrejä etuovelta kuorma-auton pysäköintipaikalle",
    "rep.check1": "Kulku ja kantomatka vahvistettu",
    "rep.check2": "Purku selvitetty",
    "rep.check3": "Särkyvät esineet merkitty",
    "rep.check4": "Ajoneuvon koko varattu",
    "rep.checklist": "Toiminnallinen tarkistuslista",
    "rep.claimHelp": "Tämä arvio ei vielä kuulu yritykselle. Lunasta se muokataksesi ja seurataksesi sitä.",
    "rep.counts": "Yhteensä esineitä & huoneita",
    "rep.deliveryAddress": "Täysi osoite",
    "rep.deliveryCarry": "Kantomatka (metriä)",
    "rep.deliveryElevator": "Hissi rakennuksessa",
    "rep.deliveryFloor": "Kerros",
    "rep.deliveryNotes": "Toimitushuomautukset",
    "rep.deliveryTitle": "Toimitus uuteen kotiin",
    "rep.elevator": "Hissi käytettävissä (sopii standardikalusteille)",
    "rep.estimateId": "Arvion tunniste",
    "rep.excluded": "Jää / poistetaan",
    "rep.export": "Vie",
    "rep.fixed": "Kiinteä hinta (tilavuus × hinta per m³)",
    "rep.floor": "Kerros",
    "rep.generalNotes": "Erityishuomautukset työtä varten",
    "rep.generalNotesPh": "Esim. tullitie, kapea portaikko, piano on kannettava",
    "rep.hourly": "Tuntihinta",
    "rep.hours": "Arvioidut tunnit",
    "rep.included": "Siirrettävät",
    "rep.internalNotes": "Sisäiset huomautukset",
    "rep.internalTitle": "Sisäinen laskelma & huomautukset",
    "rep.itemDeleted": "Kohde poistettu",
    "rep.itemsWord": "esineet",
    "rep.materials": "Tarvittavat pakkausmateriaalit",
    "rep.netVolume": "Laskettu nettotilavuus",
    "rep.packingLevel": "Laajuus",
    "rep.packingLevel.fragile": "Vain särkyvät esineet",
    "rep.packingLevel.full": "Täysi pakkaus",
    "rep.packingLevel.partial": "Osittainen pakkaus",
    "rep.packingNotes": "Erityiset esineet (taide, piano, TV)",
    "rep.packingRequested": "Haluamme apua pakkaamisessa",
    "rep.packingTitle": "Pakkaus ja materiaalit",
    "rep.pdf": "Lataa PDF-raportti",
    "rep.recommended": "Suositeltu ajoneuvo/tila (sis. lastaustekijä +25%)",
    "rep.rename": "Nimeä uudelleen",
    "rep.reportLang": "Raportin kieli",
    "rep.reportLangHelp": "Valitse kieli, jolla raportti näytetään, jaetaan ja tallennetaan. Omat muokkauksesi säilyvät.",
    "rep.requestQuote": "Pyydä sitoumukseton tarjous",
    "rep.roomsWord": "huoneet",
    "rep.saveAccess": "Tallenna pääsytiedot",
    "rep.saveExtras": "Tallenna logistiikka",
    "rep.saved": "Tallennettu",
    "rep.shareSecret": "Jaa salainen linkki",
    "rep.status.draft": "Luonnos",
    "rep.status.processed": "Käsitelty",
    "rep.status.ready": "Valmis jaettavaksi",
    "rep.storage": "Noin varastoyksikkö, koko noin",
    "rep.storageAddress": "Täysi osoite",
    "rep.storageCompany": "Varastointiyritys",
    "rep.storageContact": "Yhteyshenkilö",
    "rep.storageEnabled": "Tavarat siirtyvät välivarastoon",
    "rep.storagePhone": "Puhelin",
    "rep.storageTitle": "Välivarastointi / itsepalveluvarasto",
    "rep.tag.disassemble": "Vaatii purkamisen",
    "rep.tag.discard": "Hävitä / anna pois",
    "rep.tag.fragile": "Erittäin särkyvä",
    "rep.tag.heavy": "Raskas / vaatii 2 henkilöä",
    "rep.tender": "Tarjouspyyntötila – piilota hinnat",
    "rep.tenderHelp": "Piilottaa arvioidun hinnan ja kaikki hintalaskelmat raportista, PDF:stä ja jaetusta linkistä.",
    "rep.truck.large": "Suuri muuttoauto / perävaunu",
    "rep.truck.medium": "Muuttoauto 3,5–7,5 t",
    "rep.truck.small": "Suuri pakettiauto / pieni muuttoauto",
    "rep.truck.van": "Pieni pakettiauto (B-luokka)",
    "rep.undo": "Kumoa",
    "rep.viewBusiness": "Yritysnäkymä",
    "rep.viewCustomer": "Asiakasnäkymä",
    "res.confidence": "Luottamus",
    "res.copied": "Linkki kopioitu",
    "res.dims": "Mitat (cm)",
    "res.disclaimer": "Tämä arvio perustuu huonevideokuviin ja käyttäjän vahvistamaan tarkistuslistaan, ja se on alustava, kunnes muuttopalvelu hyväksyy sen.",
    "res.estimated": "Arvioitu hinta",
    "res.item": "Kohde",
    "res.items": "esineet",
    "res.moveRoom": "Siirrä huoneeseen",
    "res.notFound": "Arviota ei löytynyt.",
    "res.other": "Muu",
    "res.pdf": "Lataa PDF",
    "res.photos": "Kuvat",
    "res.qty": "Määrä",
    "res.renameRoom": "Nimeä huone uudelleen",
    "res.room": "Huone",
    "res.roomTotal": "Huoneen tilavuus",
    "res.share": "Kopioi jakolinkki",
    "res.title": "Tilavuusarvio",
    "res.total": "Kokonais tilavuus",
    "res.volume": "Tilavuus",
    "upload.failed": "Jokin meni pieleen. Yritä uudelleen."
  },
  "de": {
    "dash.approve": "Genehmigen",
    "dash.approved": "Genehmigt",
    "dash.claim": "Für mein Unternehmen beanspruchen",
    "dash.deleteItem": "Löschen",
    "dash.saveItem": "Speichern",
    "rep.accessTitle": "Zugang & Bedingungen",
    "rep.addNote": "Notiz hinzufügen …",
    "rep.carry": "Trageweg",
    "rep.carryHelp": "Meter von der Haustür zum LKW-Stellplatz",
    "rep.check1": "Zugang und Trageweg bestätigt",
    "rep.check2": "Demontage geklärt",
    "rep.check3": "Zerbrechliche Gegenstände markiert",
    "rep.check4": "Fahrzeuggröße gebucht",
    "rep.checklist": "Operative Checkliste",
    "rep.claimHelp": "Dieses Angebot gehört noch keinem Unternehmen. Beanspruchen Sie es, um es zu bearbeiten und nachzuverfolgen.",
    "rep.counts": "Gesamtzahl Gegenstände & Räume",
    "rep.deliveryAddress": "Vollständige Adresse",
    "rep.deliveryCarry": "Trageweg (Meter)",
    "rep.deliveryElevator": "Aufzug im Gebäude",
    "rep.deliveryFloor": "Etage",
    "rep.deliveryNotes": "Lieferhinweise",
    "rep.deliveryTitle": "Lieferung ins neue Zuhause",
    "rep.elevator": "Verfügt über einen Aufzug (passend für Standardmöbel)",
    "rep.estimateId": "Angebots-ID",
    "rep.excluded": "Bleibt / Entsorgt",
    "rep.export": "Exportieren",
    "rep.fixed": "Festpreis (Volumen × Preis pro m³)",
    "rep.floor": "Etage",
    "rep.generalNotes": "Besondere Hinweise für den Auftrag",
    "rep.generalNotesPh": "Z.B. Mautstraße, enges Treppenhaus, Klavier muss getragen werden",
    "rep.hourly": "Stundensatz",
    "rep.hours": "Geschätzte Stunden",
    "rep.included": "Wird umgezogen",
    "rep.internalNotes": "Interne Notizen",
    "rep.internalTitle": "Interne Berechnung & Notizen",
    "rep.itemDeleted": "Gegenstand gelöscht",
    "rep.itemsWord": "Gegenstände",
    "rep.materials": "Benötigtes Verpackungsmaterial",
    "rep.netVolume": "Berechnetes Nettovolumen",
    "rep.packingLevel": "Umfang",
    "rep.packingLevel.fragile": "Nur zerbrechliche Gegenstände",
    "rep.packingLevel.full": "Komplettverpackung",
    "rep.packingLevel.partial": "Teilverpackung",
    "rep.packingNotes": "Spezialgegenstände (Kunst, Klavier, TV)",
    "rep.packingRequested": "Wir wünschen Hilfe beim Einpacken",
    "rep.packingTitle": "Verpackung und Materialien",
    "rep.pdf": "PDF-Bericht herunterladen",
    "rep.recommended": "Empfohlenes Fahrzeug/Platz (inkl. Stauungsfaktor +25%)",
    "rep.rename": "Umbenennen",
    "rep.reportLang": "Berichtssprache",
    "rep.reportLangHelp": "Wählen Sie die Sprache, in der der Bericht angezeigt, geteilt und gespeichert wird. Ihre eigenen Bearbeitungen bleiben erhalten.",
    "rep.requestQuote": "Unverbindliches Angebot anfordern",
    "rep.roomsWord": "Räume",
    "rep.saveAccess": "Zugangsdetails speichern",
    "rep.saveExtras": "Logistik speichern",
    "rep.saved": "Gespeichert",
    "rep.shareSecret": "Geheimen Link teilen",
    "rep.status.draft": "Entwurf",
    "rep.status.processed": "Verarbeitet",
    "rep.status.ready": "Bereit zum Teilen",
    "rep.storage": "Ungefähr eine Lagereinheit von etwa",
    "rep.storageAddress": "Vollständige Adresse",
    "rep.storageCompany": "Lagerunternehmen",
    "rep.storageContact": "Ansprechpartner",
    "rep.storageEnabled": "Gegenstände gehen ins Zwischenlager",
    "rep.storagePhone": "Telefon",
    "rep.storageTitle": "Zwischenlagerung / Self-Storage",
    "rep.tag.disassemble": "Muss demontiert werden",
    "rep.tag.discard": "Entsorgen / Verschenken",
    "rep.tag.fragile": "Besonders zerbrechlich",
    "rep.tag.heavy": "Schwer / benötigt 2 Personen",
    "rep.tender": "Angebotsmodus – Preise verbergen",
    "rep.tenderHelp": "Verbirgt den geschätzten Preis und alle Preisberechnungen im Bericht, PDF und im geteilten Link.",
    "rep.truck.large": "Großer Umzugs-LKW / Anhänger",
    "rep.truck.medium": "Umzugs-LKW 3.5–7.5 t",
    "rep.truck.small": "Großer Transporter / kleiner Umzugs-LKW",
    "rep.truck.van": "Kleintransporter (Klasse B)",
    "rep.undo": "Rückgängig",
    "rep.viewBusiness": "Business-Ansicht",
    "rep.viewCustomer": "Kundenansicht",
    "res.confidence": "Sicherheit",
    "res.copied": "Link kopiert",
    "res.dims": "Maße (cm)",
    "res.disclaimer": "Diese Schätzung basiert auf einem Raumvideo und einer vom Benutzer bestätigten Checkliste und ist indikativ, bis das Umzugsunternehmen sie genehmigt.",
    "res.estimated": "Geschätzter Preis",
    "res.item": "Gegenstand",
    "res.items": "Gegenstände",
    "res.moveRoom": "In Raum verschieben",
    "res.notFound": "Angebot nicht gefunden.",
    "res.other": "Sonstiges",
    "res.pdf": "PDF herunterladen",
    "res.photos": "Fotos",
    "res.qty": "Menge",
    "res.renameRoom": "Raum umbenennen",
    "res.room": "Raum",
    "res.roomTotal": "Raumvolumen",
    "res.share": "Freigabelink kopieren",
    "res.title": "Volumenschätzung",
    "res.total": "Gesamtvolumen",
    "res.volume": "Volumen",
    "upload.failed": "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut."
  },
  "nl": {
    "dash.approve": "Goedkeuren",
    "dash.approved": "Goedgekeurd",
    "dash.claim": "Claimen voor mijn bedrijf",
    "dash.deleteItem": "Verwijderen",
    "dash.saveItem": "Opslaan",
    "rep.accessTitle": "Toegang & omstandigheden",
    "rep.addNote": "Notitie toevoegen…",
    "rep.carry": "Loopafstand",
    "rep.carryHelp": "Meters van voordeur tot parkeerplaats vrachtwagen",
    "rep.check1": "Toegang en loopafstand bevestigd",
    "rep.check2": "Demontage verduidelijkt",
    "rep.check3": "Breekbare items gemarkeerd",
    "rep.check4": "Voertuiggrootte geboekt",
    "rep.checklist": "Operationele checklist",
    "rep.claimHelp": "Deze offerte is nog niet aan een bedrijf gekoppeld. Claim deze om hem te bewerken en op te volgen.",
    "rep.counts": "Totaal aantal items & kamers",
    "rep.deliveryAddress": "Volledig adres",
    "rep.deliveryCarry": "Loopafstand (meters)",
    "rep.deliveryElevator": "Lift in het gebouw",
    "rep.deliveryFloor": "Verdieping",
    "rep.deliveryNotes": "Leveringsnotities",
    "rep.deliveryTitle": "Levering naar het nieuwe huis",
    "rep.elevator": "Beschikt over een lift (past standaard meubels)",
    "rep.estimateId": "Offerte-ID",
    "rep.excluded": "Blijft/wordt weggegooid",
    "rep.export": "Exporteren",
    "rep.fixed": "Vaste prijs (volume × tarief per m³)",
    "rep.floor": "Verdieping",
    "rep.generalNotes": "Speciale notities voor de opdracht",
    "rep.generalNotesPh": "Bijv. tolweg, smal trappenhuis, piano moet gedragen worden",
    "rep.hourly": "Uurtarief",
    "rep.hours": "Geschatte uren",
    "rep.included": "Wordt verhuisd",
    "rep.internalNotes": "Interne notities",
    "rep.internalTitle": "Interne berekening & notities",
    "rep.itemDeleted": "Item verwijderd",
    "rep.itemsWord": "items",
    "rep.materials": "Benodigde verpakkingsmaterialen",
    "rep.netVolume": "Berekend nettovolume",
    "rep.packingLevel": "Omvang",
    "rep.packingLevel.fragile": "Alleen breekbare items",
    "rep.packingLevel.full": "Volledige inpakservice",
    "rep.packingLevel.partial": "Gedeeltelijke inpakservice",
    "rep.packingNotes": "Speciale items (kunst, piano, TV)",
    "rep.packingRequested": "Wij willen hulp bij het inpakken",
    "rep.packingTitle": "Inpakken en materialen",
    "rep.pdf": "Download PDF rapport",
    "rep.recommended": "Aanbevolen voertuig/ruimte (incl. stuwfactor +25%)",
    "rep.rename": "Naam wijzigen",
    "rep.reportLang": "Rapporttaal",
    "rep.reportLangHelp": "Kies de taal waarin het rapport wordt weergegeven, gedeeld en opgeslagen. Uw eigen bewerkingen blijven behouden.",
    "rep.requestQuote": "Vraag een vrijblijvende offerte aan",
    "rep.roomsWord": "kamers",
    "rep.saveAccess": "Toegangsgegevens opslaan",
    "rep.saveExtras": "Logistiek opslaan",
    "rep.saved": "Opgeslagen",
    "rep.shareSecret": "Deel geheime link",
    "rep.status.draft": "Concept",
    "rep.status.processed": "Verwerkt",
    "rep.status.ready": "Klaar om te delen",
    "rep.storage": "Ongeveer een opslagruimte van",
    "rep.storageAddress": "Volledig adres",
    "rep.storageCompany": "Opslagbedrijf",
    "rep.storageContact": "Contactpersoon",
    "rep.storageEnabled": "Items gaan naar tussentijdse opslag",
    "rep.storagePhone": "Telefoon",
    "rep.storageTitle": "Tussentijdse opslag / self-storage",
    "rep.tag.disassemble": "Moet gedemonteerd worden",
    "rep.tag.discard": "Weggooien / weggeven",
    "rep.tag.fragile": "Extra breekbaar",
    "rep.tag.heavy": "Zwaar / heeft 2 personen nodig",
    "rep.tender": "Aanbestedingsmodus – verberg prijzen",
    "rep.tenderHelp": "Verbergt de geschatte prijs en alle prijsberekeningen in het rapport, de PDF en de gedeelde link.",
    "rep.truck.large": "Grote verhuiswagen / oplegger",
    "rep.truck.medium": "Verhuiswagen 3.5–7.5 t",
    "rep.truck.small": "Grote bestelwagen / kleine verhuiswagen",
    "rep.truck.van": "Kleine bestelwagen (rijbewijs B)",
    "rep.undo": "Ongedaan maken",
    "rep.viewBusiness": "Bedrijfsweergave",
    "rep.viewCustomer": "Klantweergave",
    "res.confidence": "Betrouwbaarheid",
    "res.copied": "Link gekopieerd",
    "res.dims": "Afmetingen (cm)",
    "res.disclaimer": "Deze schatting is gebaseerd op een kamervideo en een door de gebruiker geverifieerde checklist, en is indicatief totdat het verhuisbedrijf deze goedkeurt.",
    "res.estimated": "Geschatte prijs",
    "res.item": "Item",
    "res.items": "items",
    "res.moveRoom": "Verplaatsen naar kamer",
    "res.notFound": "Schatting niet gevonden.",
    "res.other": "Overig",
    "res.pdf": "Download PDF",
    "res.photos": "Foto's",
    "res.qty": "Aantal",
    "res.renameRoom": "Kamer hernoemen",
    "res.room": "Kamer",
    "res.roomTotal": "Kamer volume",
    "res.share": "Deellink kopiëren",
    "res.title": "Volumeschatting",
    "res.total": "Totaal volume",
    "res.volume": "Volume",
    "upload.failed": "Er is iets misgegaan. Probeer het opnieuw."
  },
  "fr": {
    "dash.approve": "Approuver",
    "dash.approved": "Approuvé",
    "dash.claim": "Réclamer pour mon entreprise",
    "dash.deleteItem": "Supprimer",
    "dash.saveItem": "Enregistrer",
    "rep.accessTitle": "Accès et conditions",
    "rep.addNote": "Ajouter une note...",
    "rep.carry": "Distance de portage",
    "rep.carryHelp": "Distance en mètres entre l'entrée et le stationnement du camion",
    "rep.check1": "Accès et distance de portage confirmés",
    "rep.check2": "Démontage clarifié",
    "rep.check3": "Articles fragiles signalés",
    "rep.check4": "Taille du véhicule réservé",
    "rep.checklist": "Checklist opérationnelle",
    "rep.claimHelp": "Cette estimation n'appartient pas encore à une entreprise. Réclamez-la pour la modifier et la suivre.",
    "rep.counts": "Total articles et pièces",
    "rep.deliveryAddress": "Adresse complète",
    "rep.deliveryCarry": "Distance de portage (mètres)",
    "rep.deliveryElevator": "Ascenseur dans l'immeuble",
    "rep.deliveryFloor": "Étage",
    "rep.deliveryNotes": "Notes de livraison",
    "rep.deliveryTitle": "Livraison au nouveau domicile",
    "rep.elevator": "Dispose d'un ascenseur (peut contenir un meuble standard)",
    "rep.estimateId": "ID de l'estimation",
    "rep.excluded": "Reste / Jeté",
    "rep.export": "Exporter",
    "rep.fixed": "Prix fixe (volume × tarif par m³)",
    "rep.floor": "Étage",
    "rep.generalNotes": "Notes spéciales pour la tâche",
    "rep.generalNotesPh": "Ex: péage, cage d'escalier étroite, piano à porter",
    "rep.hourly": "Tarif horaire",
    "rep.hours": "Heures estimées",
    "rep.included": "À déménager",
    "rep.internalNotes": "Notes internes",
    "rep.internalTitle": "Calcul et notes internes",
    "rep.itemDeleted": "Article supprimé",
    "rep.itemsWord": "articles",
    "rep.materials": "Matériel d'emballage nécessaire",
    "rep.netVolume": "Volume net calculé",
    "rep.packingLevel": "Portée",
    "rep.packingLevel.fragile": "Articles fragiles uniquement",
    "rep.packingLevel.full": "Emballage complet",
    "rep.packingLevel.partial": "Emballage partiel",
    "rep.packingNotes": "Articles spéciaux (art, piano, TV)",
    "rep.packingRequested": "Nous souhaitons de l'aide pour l'emballage",
    "rep.packingTitle": "Emballage et matériel",
    "rep.pdf": "Télécharger le rapport PDF",
    "rep.recommended": "Véhicule/espace recommandé (incl. coefficient de remplissage +25%)",
    "rep.rename": "Renommer",
    "rep.reportLang": "Langue du rapport",
    "rep.reportLangHelp": "Choisissez la langue dans laquelle le rapport est affiché, partagé et enregistré. Vos propres modifications sont conservées.",
    "rep.requestQuote": "Demander un devis sans engagement",
    "rep.roomsWord": "pièces",
    "rep.saveAccess": "Enregistrer les détails d'accès",
    "rep.saveExtras": "Enregistrer la logistique",
    "rep.saved": "Enregistré",
    "rep.shareSecret": "Partager le lien secret",
    "rep.status.draft": "Brouillon",
    "rep.status.processed": "Traité",
    "rep.status.ready": "Prêt à partager",
    "rep.storage": "Un entrepôt d'environ",
    "rep.storageAddress": "Adresse complète",
    "rep.storageCompany": "Société de stockage",
    "rep.storageContact": "Personne de contact",
    "rep.storageEnabled": "Articles placés en stockage temporaire",
    "rep.storagePhone": "Téléphone",
    "rep.storageTitle": "Garde-meuble / Self-stockage",
    "rep.tag.disassemble": "Nécessite un démontage",
    "rep.tag.discard": "Jeter / donner",
    "rep.tag.fragile": "Très fragile",
    "rep.tag.heavy": "Lourd / nécessite 2 personnes",
    "rep.tender": "Mode appel d'offres – masquer les prix",
    "rep.tenderHelp": "Masque le prix estimé et tous les calculs de prix dans le rapport, le PDF et le lien partagé.",
    "rep.truck.large": "Grand camion de déménagement / remorque",
    "rep.truck.medium": "Camion de déménagement 3,5–7,5 t",
    "rep.truck.small": "Grande camionnette / petit camion de déménagement",
    "rep.truck.van": "Petite camionnette (classe B)",
    "rep.undo": "Annuler",
    "rep.viewBusiness": "Vue entreprise",
    "rep.viewCustomer": "Vue client",
    "res.confidence": "Confiance",
    "res.copied": "Lien copié",
    "res.dims": "Dimensions (cm)",
    "res.disclaimer": "Cette estimation est basée sur une vidéo de la pièce et une checklist vérifiée par l'utilisateur, et est indicative jusqu'à son approbation par l'entreprise de déménagement.",
    "res.estimated": "Prix estimé",
    "res.item": "Article",
    "res.items": "articles",
    "res.moveRoom": "Déplacer vers la pièce",
    "res.notFound": "Estimation introuvable.",
    "res.other": "Autre",
    "res.pdf": "Télécharger PDF",
    "res.photos": "Photos",
    "res.qty": "Qté",
    "res.renameRoom": "Renommer la pièce",
    "res.room": "Pièce",
    "res.roomTotal": "Volume de la pièce",
    "res.share": "Copier le lien de partage",
    "res.title": "Estimation du volume",
    "res.total": "Volume total",
    "res.volume": "Volume",
    "upload.failed": "Une erreur est survenue. Veuillez réessayer."
  },
  "pl": {
    "dash.approve": "Zatwierdź",
    "dash.approved": "Zatwierdzono",
    "dash.claim": "Przypisz do mojej firmy",
    "dash.deleteItem": "Usuń",
    "dash.saveItem": "Zapisz",
    "rep.accessTitle": "Dostęp i warunki",
    "rep.addNote": "Dodaj notatkę…",
    "rep.carry": "Dystans przenoszenia",
    "rep.carryHelp": "Metry od drzwi wejściowych do miejsca parkingowego dla ciężarówki",
    "rep.check1": "Potwierdzono dostęp i dystans przenoszenia",
    "rep.check2": "Wyjaśniono kwestię demontażu",
    "rep.check3": "Oznaczono przedmioty delikatne",
    "rep.check4": "Zarezerwowano rozmiar pojazdu",
    "rep.checklist": "Lista kontrolna operacji",
    "rep.claimHelp": "To kosztorys nie jest jeszcze przypisany do żadnej firmy. Przypisz go, aby edytować i śledzić jego status.",
    "rep.counts": "Łączna liczba przedmiotów i pomieszczeń",
    "rep.deliveryAddress": "Pełny adres",
    "rep.deliveryCarry": "Dystans przenoszenia (metry)",
    "rep.deliveryElevator": "Winda w budynku",
    "rep.deliveryFloor": "Piętro",
    "rep.deliveryNotes": "Notatki dotyczące dostawy",
    "rep.deliveryTitle": "Dostawa do nowego domu",
    "rep.elevator": "Posiada windę (mieści standardowe meble)",
    "rep.estimateId": "ID kosztorysu",
    "rep.excluded": "Pozostaje / do wyrzucenia",
    "rep.export": "Eksportuj",
    "rep.fixed": "Cena stała (objętość × stawka za m³)",
    "rep.floor": "Piętro",
    "rep.generalNotes": "Uwagi ogólne do zlecenia",
    "rep.generalNotesPh": "Np. płatna droga, wąska klatka schodowa, pianino musi być przeniesione",
    "rep.hourly": "Stawka godzinowa",
    "rep.hours": "Szacowane godziny",
    "rep.included": "Do przeniesienia",
    "rep.internalNotes": "Notatki wewnętrzne",
    "rep.internalTitle": "Kalkulacja wewnętrzna i notatki",
    "rep.itemDeleted": "Przedmiot usunięty",
    "rep.itemsWord": "przedmioty",
    "rep.materials": "Potrzebne materiały do pakowania",
    "rep.netVolume": "Obliczona objętość netto",
    "rep.packingLevel": "Zakres",
    "rep.packingLevel.fragile": "Tylko przedmioty delikatne",
    "rep.packingLevel.full": "Pełne pakowanie",
    "rep.packingLevel.partial": "Częściowe pakowanie",
    "rep.packingNotes": "Przedmioty specjalne (sztuka, pianino, telewizor)",
    "rep.packingRequested": "Chcemy pomocy w pakowaniu",
    "rep.packingTitle": "Pakowanie i materiały",
    "rep.pdf": "Pobierz raport PDF",
    "rep.recommended": "Zalecany pojazd/przestrzeń (w tym współczynnik składowania +25%)",
    "rep.rename": "Zmień nazwę",
    "rep.reportLang": "Język raportu",
    "rep.reportLangHelp": "Wybierz język, w którym raport jest wyświetlany, udostępniany i zapisywany. Twoje edycje zostaną zachowane.",
    "rep.requestQuote": "Poproś o niezobowiązującą wycenę",
    "rep.roomsWord": "pomieszczenia",
    "rep.saveAccess": "Zapisz szczegóły dostępu",
    "rep.saveExtras": "Zapisz logistykę",
    "rep.saved": "Zapisano",
    "rep.shareSecret": "Udostępnij tajny link",
    "rep.status.draft": "Szkic",
    "rep.status.processed": "Przetworzono",
    "rep.status.ready": "Gotowy do udostępnienia",
    "rep.storage": "Mniej więcej magazyn o powierzchni",
    "rep.storageAddress": "Pełny adres",
    "rep.storageCompany": "Firma magazynująca",
    "rep.storageContact": "Osoba kontaktowa",
    "rep.storageEnabled": "Przedmioty trafiają do magazynu tymczasowego",
    "rep.storagePhone": "Telefon",
    "rep.storageTitle": "Magazyn tymczasowy / samoobsługowy",
    "rep.tag.disassemble": "Wymaga demontażu",
    "rep.tag.discard": "Do wyrzucenia / oddania",
    "rep.tag.fragile": "Bardzo delikatne",
    "rep.tag.heavy": "Ciężkie / wymaga 2 osób",
    "rep.tender": "Tryb przetargu – ukryj ceny",
    "rep.tenderHelp": "Ukrywa szacowaną cenę oraz wszystkie kalkulacje cenowe w raporcie, pliku PDF i udostępnionym linku.",
    "rep.truck.large": "Duża ciężarówka przeprowadzkowa / przyczepa",
    "rep.truck.medium": "Ciężarówka przeprowadzkowa 3.5–7.5 t",
    "rep.truck.small": "Duży van / mała ciężarówka przeprowadzkowa",
    "rep.truck.van": "Mały van (klasa B)",
    "rep.undo": "Cofnij",
    "rep.viewBusiness": "Widok biznesowy",
    "rep.viewCustomer": "Widok klienta",
    "res.confidence": "Pewność",
    "res.copied": "Link skopiowany",
    "res.dims": "Wymiary (cm)",
    "res.disclaimer": "Niniejszy kosztorys opiera się na nagraniu wideo pomieszczenia i zweryfikowanej przez użytkownika liście kontrolnej, ma charakter orientacyjny do momentu zatwierdzenia przez firmę przeprowadzkową.",
    "res.estimated": "Szacowana cena",
    "res.item": "Przedmiot",
    "res.items": "przedmioty",
    "res.moveRoom": "Przenieś do pokoju",
    "res.notFound": "Kosztorys nie znaleziony.",
    "res.other": "Inne",
    "res.pdf": "Pobierz PDF",
    "res.photos": "Zdjęcia",
    "res.qty": "Ilość",
    "res.renameRoom": "Zmień nazwę pokoju",
    "res.room": "Pomieszczenie",
    "res.roomTotal": "Objętość pomieszczenia",
    "res.share": "Kopiuj link do udostępniania",
    "res.title": "Szacowanie objętości",
    "res.total": "Całkowita objętość",
    "res.volume": "Objętość",
    "upload.failed": "Coś poszło nie tak. Spróbuj ponownie."
  },
  "es": {
    "dash.approve": "Aprobar",
    "dash.approved": "Aprobado",
    "dash.claim": "Reclamar para mi empresa",
    "dash.deleteItem": "Eliminar",
    "dash.saveItem": "Guardar",
    "rep.accessTitle": "Acceso y condiciones",
    "rep.addNote": "Añadir una nota…",
    "rep.carry": "Distancia de acarreo",
    "rep.carryHelp": "Metros desde la puerta principal hasta el aparcamiento del camión",
    "rep.check1": "Acceso y distancia de acarreo confirmados",
    "rep.check2": "Desmontaje aclarado",
    "rep.check3": "Artículos frágiles señalados",
    "rep.check4": "Tamaño de vehículo reservado",
    "rep.checklist": "Lista de verificación operativa",
    "rep.claimHelp": "Este presupuesto aún no pertenece a ninguna empresa. Reclámelo para editarlo y darle seguimiento.",
    "rep.counts": "Total de artículos y habitaciones",
    "rep.deliveryAddress": "Dirección completa",
    "rep.deliveryCarry": "Distancia de acarreo (metros)",
    "rep.deliveryElevator": "Ascensor en el edificio",
    "rep.deliveryFloor": "Piso",
    "rep.deliveryNotes": "Notas de entrega",
    "rep.deliveryTitle": "Entrega al nuevo domicilio",
    "rep.elevator": "Tiene ascensor (cabe mobiliario estándar)",
    "rep.estimateId": "ID de presupuesto",
    "rep.excluded": "Se queda / Se desecha",
    "rep.export": "Exportar",
    "rep.fixed": "Precio fijo (volumen × tarifa por m³)",
    "rep.floor": "Piso",
    "rep.generalNotes": "Notas especiales para el trabajo",
    "rep.generalNotesPh": "Ej. peaje, escalera estrecha, piano debe ser cargado",
    "rep.hourly": "Tarifa por hora",
    "rep.hours": "Horas estimadas",
    "rep.included": "A trasladar",
    "rep.internalNotes": "Notas internas",
    "rep.internalTitle": "Cálculo y notas internas",
    "rep.itemDeleted": "Artículo eliminado",
    "rep.itemsWord": "artículos",
    "rep.materials": "Materiales de embalaje necesarios",
    "rep.netVolume": "Volumen neto calculado",
    "rep.packingLevel": "Alcance",
    "rep.packingLevel.fragile": "Solo artículos frágiles",
    "rep.packingLevel.full": "Embalaje completo",
    "rep.packingLevel.partial": "Embalaje parcial",
    "rep.packingNotes": "Artículos especiales (arte, piano, TV)",
    "rep.packingRequested": "Queremos ayuda con el embalaje",
    "rep.packingTitle": "Embalaje y materiales",
    "rep.pdf": "Descargar informe PDF",
    "rep.recommended": "Vehículo/espacio recomendado (incl. factor de estiba +25%)",
    "rep.rename": "Renombrar",
    "rep.reportLang": "Idioma del informe",
    "rep.reportLangHelp": "Elija el idioma en el que se muestra, comparte y guarda el informe. Sus propias ediciones se conservan.",
    "rep.requestQuote": "Solicitar presupuesto sin compromiso",
    "rep.roomsWord": "habitaciones",
    "rep.saveAccess": "Guardar detalles de acceso",
    "rep.saveExtras": "Guardar logística",
    "rep.saved": "Guardado",
    "rep.shareSecret": "Compartir enlace secreto",
    "rep.status.draft": "Borrador",
    "rep.status.processed": "Procesado",
    "rep.status.ready": "Listo para compartir",
    "rep.storage": "Aproximadamente un trastero de unos",
    "rep.storageAddress": "Dirección completa",
    "rep.storageCompany": "Empresa de almacenamiento",
    "rep.storageContact": "Persona de contacto",
    "rep.storageEnabled": "Los artículos van a almacenamiento temporal",
    "rep.storagePhone": "Teléfono",
    "rep.storageTitle": "Almacenamiento temporal / Guardamuebles",
    "rep.tag.disassemble": "Necesita desmontaje",
    "rep.tag.discard": "Desechar / Donar",
    "rep.tag.fragile": "Extra frágil",
    "rep.tag.heavy": "Pesado / Necesita 2 personas",
    "rep.tender": "Modo licitación – ocultar precios",
    "rep.tenderHelp": "Oculta el precio estimado y todos los cálculos de precios en el informe, PDF y enlace compartido.",
    "rep.truck.large": "Camión de mudanzas grande / remolque",
    "rep.truck.medium": "Camión de mudanzas 3.5–7.5 t",
    "rep.truck.small": "Furgoneta grande / camión de mudanzas pequeño",
    "rep.truck.van": "Furgoneta pequeña (clase B)",
    "rep.undo": "Deshacer",
    "rep.viewBusiness": "Vista de empresa",
    "rep.viewCustomer": "Vista de cliente",
    "res.confidence": "Confianza",
    "res.copied": "Enlace copiado",
    "res.dims": "Dimensiones (cm)",
    "res.disclaimer": "Este presupuesto se basa en un vídeo de la habitación y una lista de verificación verificada por el usuario, y es indicativo hasta que la empresa de mudanzas lo apruebe.",
    "res.estimated": "Precio estimado",
    "res.item": "Artículo",
    "res.items": "artículos",
    "res.moveRoom": "Mover a habitación",
    "res.notFound": "Presupuesto no encontrado.",
    "res.other": "Otros",
    "res.pdf": "Descargar PDF",
    "res.photos": "Fotos",
    "res.qty": "Cant.",
    "res.renameRoom": "Renombrar habitación",
    "res.room": "Habitación",
    "res.roomTotal": "Volumen de la habitación",
    "res.share": "Copiar enlace para compartir",
    "res.title": "Estimación de volumen",
    "res.total": "Volumen total",
    "res.volume": "Volumen",
    "upload.failed": "Algo salió mal. Por favor, inténtelo de nuevo."
  },
  "it": {
    "dash.approve": "Approva",
    "dash.approved": "Approvato",
    "dash.claim": "Reclama per la mia azienda",
    "dash.deleteItem": "Elimina",
    "dash.saveItem": "Salva",
    "rep.accessTitle": "Accesso e condizioni",
    "rep.addNote": "Aggiungi una nota…",
    "rep.carry": "Distanza di trasporto",
    "rep.carryHelp": "Metri dalla porta d'ingresso al parcheggio del camion",
    "rep.check1": "Accesso e distanza di trasporto confermati",
    "rep.check2": "Smontaggio chiarito",
    "rep.check3": "Articoli fragili segnalati",
    "rep.check4": "Dimensioni veicolo prenotate",
    "rep.checklist": "Lista di controllo operativa",
    "rep.claimHelp": "Questa stima non appartiene ancora a un'azienda. Reclamala per modificarla e seguirla.",
    "rep.counts": "Totale articoli e stanze",
    "rep.deliveryAddress": "Indirizzo completo",
    "rep.deliveryCarry": "Distanza di trasporto (metri)",
    "rep.deliveryElevator": "Ascensore nell'edificio",
    "rep.deliveryFloor": "Piano",
    "rep.deliveryNotes": "Note di consegna",
    "rep.deliveryTitle": "Consegna alla nuova casa",
    "rep.elevator": "Dispone di ascensore (adatto a mobili standard)",
    "rep.estimateId": "ID stima",
    "rep.excluded": "Resta / Scartato",
    "rep.export": "Esporta",
    "rep.fixed": "Prezzo fisso (volume × tariffa per m³)",
    "rep.floor": "Piano",
    "rep.generalNotes": "Note speciali per il lavoro",
    "rep.generalNotesPh": "Es. strada a pedaggio, vano scale stretto, il pianoforte deve essere trasportato",
    "rep.hourly": "Tariffa oraria",
    "rep.hours": "Ore stimate",
    "rep.included": "Da traslocare",
    "rep.internalNotes": "Note interne",
    "rep.internalTitle": "Calcolo e note interne",
    "rep.itemDeleted": "Articolo eliminato",
    "rep.itemsWord": "articoli",
    "rep.materials": "Materiali di imballaggio necessari",
    "rep.netVolume": "Volume netto calcolato",
    "rep.packingLevel": "Ambito",
    "rep.packingLevel.fragile": "Solo articoli fragili",
    "rep.packingLevel.full": "Imballaggio completo",
    "rep.packingLevel.partial": "Imballaggio parziale",
    "rep.packingNotes": "Articoli speciali (arte, pianoforte, TV)",
    "rep.packingRequested": "Desideriamo aiuto con l'imballaggio",
    "rep.packingTitle": "Imballaggio e materiali",
    "rep.pdf": "Scarica rapporto PDF",
    "rep.recommended": "Veicolo/spazio consigliato (incl. fattore di stivaggio +25%)",
    "rep.rename": "Rinomina",
    "rep.reportLang": "Lingua del rapporto",
    "rep.reportLangHelp": "Scegli la lingua in cui il rapporto viene mostrato, condiviso e salvato. Le tue modifiche personali vengono mantenute.",
    "rep.requestQuote": "Richiedi un preventivo senza impegno",
    "rep.roomsWord": "stanze",
    "rep.saveAccess": "Salva dettagli accesso",
    "rep.saveExtras": "Salva logistica",
    "rep.saved": "Salvato",
    "rep.shareSecret": "Condividi link segreto",
    "rep.status.draft": "Bozza",
    "rep.status.processed": "Elaborato",
    "rep.status.ready": "Pronto per la condivisione",
    "rep.storage": "Circa un'unità di stoccaggio di circa",
    "rep.storageAddress": "Indirizzo completo",
    "rep.storageCompany": "Azienda di stoccaggio",
    "rep.storageContact": "Persona di contatto",
    "rep.storageEnabled": "Articoli vanno in deposito temporaneo",
    "rep.storagePhone": "Telefono",
    "rep.storageTitle": "Deposito temporaneo / self-storage",
    "rep.tag.disassemble": "Richiede smontaggio",
    "rep.tag.discard": "Scarta / Regala",
    "rep.tag.fragile": "Extra fragile",
    "rep.tag.heavy": "Pesante / richiede 2 persone",
    "rep.tender": "Modalità gara – nascondi prezzi",
    "rep.tenderHelp": "Nasconde il prezzo stimato e tutti i calcoli di prezzo nel rapporto, PDF e link condiviso.",
    "rep.truck.large": "Camion traslochi grande / rimorchio",
    "rep.truck.medium": "Camion traslochi 3.5–7.5 t",
    "rep.truck.small": "Furgone grande / camion traslochi piccolo",
    "rep.truck.van": "Furgone piccolo (patente B)",
    "rep.undo": "Annulla",
    "rep.viewBusiness": "Vista azienda",
    "rep.viewCustomer": "Vista cliente",
    "res.confidence": "Affidabilità",
    "res.copied": "Link copiato",
    "res.dims": "Dimensioni (cm)",
    "res.disclaimer": "Questa stima è basata su video della stanza e una lista di controllo verificata dall'utente, ed è indicativa fino all'approvazione da parte della ditta di traslochi.",
    "res.estimated": "Prezzo stimato",
    "res.item": "Articolo",
    "res.items": "articoli",
    "res.moveRoom": "Sposta nella stanza",
    "res.notFound": "Stima non trovata.",
    "res.other": "Altro",
    "res.pdf": "Scarica PDF",
    "res.photos": "Foto",
    "res.qty": "Qtà",
    "res.renameRoom": "Rinomina stanza",
    "res.room": "Stanza",
    "res.roomTotal": "Volume stanza",
    "res.share": "Copia link di condivisione",
    "res.title": "Stima del volume",
    "res.total": "Volume totale",
    "res.volume": "Volume",
    "upload.failed": "Qualcosa è andato storto. Riprova."
  },
  "pt": {
    "dash.approve": "Aprovar",
    "dash.approved": "Aprovado",
    "dash.claim": "Reclamar para a minha empresa",
    "dash.deleteItem": "Excluir",
    "dash.saveItem": "Guardar",
    "rep.accessTitle": "Acesso e condições",
    "rep.addNote": "Adicionar uma nota...",
    "rep.carry": "Distância de transporte",
    "rep.carryHelp": "Metros da porta da frente até ao parque de estacionamento do camião",
    "rep.check1": "Acesso e distância de transporte confirmados",
    "rep.check2": "Desmontagem esclarecida",
    "rep.check3": "Artigos frágeis sinalizados",
    "rep.check4": "Tamanho do veículo reservado",
    "rep.checklist": "Lista de verificação operacional",
    "rep.claimHelp": "Este orçamento ainda não pertence a uma empresa. Reclame-o para o editar e acompanhar.",
    "rep.counts": "Total de artigos e divisões",
    "rep.deliveryAddress": "Morada completa",
    "rep.deliveryCarry": "Distância de transporte (metros)",
    "rep.deliveryElevator": "Elevador no edifício",
    "rep.deliveryFloor": "Andar",
    "rep.deliveryNotes": "Notas de entrega",
    "rep.deliveryTitle": "Entrega na nova casa",
    "rep.elevator": "Possui elevador (cabe mobiliário padrão)",
    "rep.estimateId": "ID do orçamento",
    "rep.excluded": "Permanecem / descartados",
    "rep.export": "Exportar",
    "rep.fixed": "Preço fixo (volume × taxa por m³)",
    "rep.floor": "Andar",
    "rep.generalNotes": "Notas especiais para o trabalho",
    "rep.generalNotesPh": "Ex: portagem, escada estreita, piano deve ser transportado",
    "rep.hourly": "Tarifa horária",
    "rep.hours": "Horas estimadas",
    "rep.included": "A transportar",
    "rep.internalNotes": "Notas internas",
    "rep.internalTitle": "Cálculo e notas internas",
    "rep.itemDeleted": "Artigo excluído",
    "rep.itemsWord": "artigos",
    "rep.materials": "Materiais de embalagem necessários",
    "rep.netVolume": "Volume líquido calculado",
    "rep.packingLevel": "Âmbito",
    "rep.packingLevel.fragile": "Apenas artigos frágeis",
    "rep.packingLevel.full": "Embalagem completa",
    "rep.packingLevel.partial": "Embalagem parcial",
    "rep.packingNotes": "Artigos especiais (arte, piano, TV)",
    "rep.packingRequested": "Queremos ajuda com a embalagem",
    "rep.packingTitle": "Embalagem e materiais",
    "rep.pdf": "Descarregar relatório em PDF",
    "rep.recommended": "Veículo/espaço recomendado (incluindo fator de estiva +25%)",
    "rep.rename": "Renomear",
    "rep.reportLang": "Idioma do relatório",
    "rep.reportLangHelp": "Escolha o idioma em que o relatório é mostrado, partilhado e guardado. As suas edições são mantidas.",
    "rep.requestQuote": "Pedir um orçamento sem compromisso",
    "rep.roomsWord": "divisões",
    "rep.saveAccess": "Guardar detalhes de acesso",
    "rep.saveExtras": "Guardar logística",
    "rep.saved": "Guardado",
    "rep.shareSecret": "Partilhar link secreto",
    "rep.status.draft": "Rascunho",
    "rep.status.processed": "Processado",
    "rep.status.ready": "Pronto para partilhar",
    "rep.storage": "Aproximadamente um espaço de armazenagem de cerca de",
    "rep.storageAddress": "Morada completa",
    "rep.storageCompany": "Empresa de armazenagem",
    "rep.storageContact": "Pessoa de contacto",
    "rep.storageEnabled": "Artigos vão para armazenagem temporária",
    "rep.storagePhone": "Telefone",
    "rep.storageTitle": "Armazenagem temporária / self-storage",
    "rep.tag.disassemble": "Precisa de desmontagem",
    "rep.tag.discard": "Descartar / doar",
    "rep.tag.fragile": "Extra frágil",
    "rep.tag.heavy": "Pesado / precisa de 2 pessoas",
    "rep.tender": "Modo de concurso – ocultar preços",
    "rep.tenderHelp": "Oculta o preço estimado e todos os cálculos de preço no relatório, PDF e link partilhado.",
    "rep.truck.large": "Camião de mudanças grande / reboque",
    "rep.truck.medium": "Camião de mudanças 3.5–7.5 t",
    "rep.truck.small": "Carrinha grande / camião de mudanças pequeno",
    "rep.truck.van": "Carrinha pequena (classe B)",
    "rep.undo": "Desfazer",
    "rep.viewBusiness": "Vista de negócio",
    "rep.viewCustomer": "Vista de cliente",
    "res.confidence": "Confiabilidade",
    "res.copied": "Link copiado",
    "res.dims": "Dimensões (cm)",
    "res.disclaimer": "Este orçamento baseia-se em vídeo do espaço e numa lista de verificação verificada pelo utilizador, sendo indicativo até ser aprovado pela empresa de mudanças.",
    "res.estimated": "Preço estimado",
    "res.item": "Artigo",
    "res.items": "artigos",
    "res.moveRoom": "Mover para a divisão",
    "res.notFound": "Orçamento não encontrado.",
    "res.other": "Outros",
    "res.pdf": "Descarregar PDF",
    "res.photos": "Fotos",
    "res.qty": "Qtd",
    "res.renameRoom": "Renomear divisão",
    "res.room": "Divisão",
    "res.roomTotal": "Volume da divisão",
    "res.share": "Copiar link de partilha",
    "res.title": "Orçamento de volume",
    "res.total": "Volume total",
    "res.volume": "Volume",
    "upload.failed": "Algo correu mal. Por favor, tente novamente."
  }
};
