/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatabehandlingRouteImport } from './routes/databehandling'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FlyttebilKalkulatorRouteImport } from './routes/flyttebil-kalkulator'
import { Route as HjelpRouteImport } from './routes/hjelp'
import { Route as KjopsvilkarRouteImport } from './routes/kjopsvilkar'
import { Route as MovingInventoryListRouteImport } from './routes/moving-inventory-list'
import { Route as NoRouteImport } from './routes/no'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as EnMovingVanCalculatorRouteImport } from './routes/en.moving-van-calculator'
import { Route as EstimateIdRouteImport } from './routes/estimate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabehandlingRoute = DatabehandlingRouteImport.update({
  id: '/databehandling',
  path: '/databehandling',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyttebilKalkulatorRoute = FlyttebilKalkulatorRouteImport.update({
  id: '/flyttebil-kalkulator',
  path: '/flyttebil-kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const HjelpRoute = HjelpRouteImport.update({
  id: '/hjelp',
  path: '/hjelp',
  getParentRoute: () => rootRouteImport,
} as any)
const KjopsvilkarRoute = KjopsvilkarRouteImport.update({
  id: '/kjopsvilkar',
  path: '/kjopsvilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingInventoryListRoute = MovingInventoryListRouteImport.update({
  id: '/moving-inventory-list',
  path: '/moving-inventory-list',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRoute = NoRouteImport.update({
  id: '/no',
  path: '/no',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const EnMovingVanCalculatorRoute = EnMovingVanCalculatorRouteImport.update({
  id: '/en/moving-van-calculator',
  path: '/en/moving-van-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateIdRoute = EstimateIdRouteImport.update({
  id: '/estimate/$id',
  path: '/estimate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/databehandling': typeof DatabehandlingRoute
  '/demo': typeof DemoRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/hjelp': typeof HjelpRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/databehandling': typeof DatabehandlingRoute
  '/demo': typeof DemoRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/hjelp': typeof HjelpRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/databehandling': typeof DatabehandlingRoute
  '/demo': typeof DemoRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/hjelp': typeof HjelpRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/databehandling'
    | '/demo'
    | '/flyttebil-kalkulator'
    | '/hjelp'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pricing'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/databehandling'
    | '/demo'
    | '/flyttebil-kalkulator'
    | '/hjelp'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pricing'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/databehandling'
    | '/demo'
    | '/flyttebil-kalkulator'
    | '/hjelp'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pricing'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DatabehandlingRoute: typeof DatabehandlingRoute
  DemoRoute: typeof DemoRoute
  FlyttebilKalkulatorRoute: typeof FlyttebilKalkulatorRoute
  HjelpRoute: typeof HjelpRoute
  KjopsvilkarRoute: typeof KjopsvilkarRoute
  MovingInventoryListRoute: typeof MovingInventoryListRoute
  NoRoute: typeof NoRoute
  OmOssRoute: typeof OmOssRoute
  PersonvernRoute: typeof PersonvernRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
  VilkarRoute: typeof VilkarRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EnMovingVanCalculatorRoute: typeof EnMovingVanCalculatorRoute
  EstimateIdRoute: typeof EstimateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databehandling': {
      id: '/databehandling'
      path: '/databehandling'
      fullPath: '/databehandling'
      preLoaderRoute: typeof DatabehandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyttebil-kalkulator': {
      id: '/flyttebil-kalkulator'
      path: '/flyttebil-kalkulator'
      fullPath: '/flyttebil-kalkulator'
      preLoaderRoute: typeof FlyttebilKalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hjelp': {
      id: '/hjelp'
      path: '/hjelp'
      fullPath: '/hjelp'
      preLoaderRoute: typeof HjelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kjopsvilkar': {
      id: '/kjopsvilkar'
      path: '/kjopsvilkar'
      fullPath: '/kjopsvilkar'
      preLoaderRoute: typeof KjopsvilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-inventory-list': {
      id: '/moving-inventory-list'
      path: '/moving-inventory-list'
      fullPath: '/moving-inventory-list'
      preLoaderRoute: typeof MovingInventoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no': {
      id: '/no'
      path: '/no'
      fullPath: '/no'
      preLoaderRoute: typeof NoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/en/moving-van-calculator': {
      id: '/en/moving-van-calculator'
      path: '/en/moving-van-calculator'
      fullPath: '/en/moving-van-calculator'
      preLoaderRoute: typeof EnMovingVanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$id': {
      id: '/estimate/$id'
      path: '/estimate/$id'
      fullPath: '/estimate/$id'
      preLoaderRoute: typeof EstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DatabehandlingRoute: DatabehandlingRoute,
  DemoRoute: DemoRoute,
  FlyttebilKalkulatorRoute: FlyttebilKalkulatorRoute,
  HjelpRoute: HjelpRoute,
  KjopsvilkarRoute: KjopsvilkarRoute,
  MovingInventoryListRoute: MovingInventoryListRoute,
  NoRoute: NoRoute,
  OmOssRoute: OmOssRoute,
  PersonvernRoute: PersonvernRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
  VilkarRoute: VilkarRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EnMovingVanCalculatorRoute: EnMovingVanCalculatorRoute,
  EstimateIdRoute: EstimateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
