/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatabehandlingRouteImport } from './routes/databehandling'
import { Route as DeRouteImport } from './routes/de'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DkRouteImport } from './routes/dk'
import { Route as EsRouteImport } from './routes/es'
import { Route as FiRouteImport } from './routes/fi'
import { Route as FlyttebilKalkulatorRouteImport } from './routes/flyttebil-kalkulator'
import { Route as FrRouteImport } from './routes/fr'
import { Route as HjelpRouteImport } from './routes/hjelp'
import { Route as ItRouteImport } from './routes/it'
import { Route as KjopsvilkarRouteImport } from './routes/kjopsvilkar'
import { Route as MovingInventoryListRouteImport } from './routes/moving-inventory-list'
import { Route as NlRouteImport } from './routes/nl'
import { Route as NoRouteImport } from './routes/no'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as PlRouteImport } from './routes/pl'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PtRouteImport } from './routes/pt'
import { Route as SeRouteImport } from './routes/se'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as EnMovingVanCalculatorRouteImport } from './routes/en.moving-van-calculator'
import { Route as EstimateIdRouteImport } from './routes/estimate.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabehandlingRoute = DatabehandlingRouteImport.update({
  id: '/databehandling',
  path: '/databehandling',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DkRoute = DkRouteImport.update({
  id: '/dk',
  path: '/dk',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const FiRoute = FiRouteImport.update({
  id: '/fi',
  path: '/fi',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyttebilKalkulatorRoute = FlyttebilKalkulatorRouteImport.update({
  id: '/flyttebil-kalkulator',
  path: '/flyttebil-kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const HjelpRoute = HjelpRouteImport.update({
  id: '/hjelp',
  path: '/hjelp',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const KjopsvilkarRoute = KjopsvilkarRouteImport.update({
  id: '/kjopsvilkar',
  path: '/kjopsvilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingInventoryListRoute = MovingInventoryListRouteImport.update({
  id: '/moving-inventory-list',
  path: '/moving-inventory-list',
  getParentRoute: () => rootRouteImport,
} as any)
const NlRoute = NlRouteImport.update({
  id: '/nl',
  path: '/nl',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRoute = NoRouteImport.update({
  id: '/no',
  path: '/no',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const PlRoute = PlRouteImport.update({
  id: '/pl',
  path: '/pl',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const SeRoute = SeRouteImport.update({
  id: '/se',
  path: '/se',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const EnMovingVanCalculatorRoute = EnMovingVanCalculatorRouteImport.update({
  id: '/en/moving-van-calculator',
  path: '/en/moving-van-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateIdRoute = EstimateIdRouteImport.update({
  id: '/estimate/$id',
  path: '/estimate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/databehandling': typeof DatabehandlingRoute
  '/de': typeof DeRoute
  '/demo': typeof DemoRoute
  '/dk': typeof DkRoute
  '/es': typeof EsRoute
  '/fi': typeof FiRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/fr': typeof FrRoute
  '/hjelp': typeof HjelpRoute
  '/it': typeof ItRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/nl': typeof NlRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pl': typeof PlRoute
  '/pricing': typeof PricingRoute
  '/pt': typeof PtRoute
  '/se': typeof SeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/databehandling': typeof DatabehandlingRoute
  '/de': typeof DeRoute
  '/demo': typeof DemoRoute
  '/dk': typeof DkRoute
  '/es': typeof EsRoute
  '/fi': typeof FiRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/fr': typeof FrRoute
  '/hjelp': typeof HjelpRoute
  '/it': typeof ItRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/nl': typeof NlRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pl': typeof PlRoute
  '/pricing': typeof PricingRoute
  '/pt': typeof PtRoute
  '/se': typeof SeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/databehandling': typeof DatabehandlingRoute
  '/de': typeof DeRoute
  '/demo': typeof DemoRoute
  '/dk': typeof DkRoute
  '/es': typeof EsRoute
  '/fi': typeof FiRoute
  '/flyttebil-kalkulator': typeof FlyttebilKalkulatorRoute
  '/fr': typeof FrRoute
  '/hjelp': typeof HjelpRoute
  '/it': typeof ItRoute
  '/kjopsvilkar': typeof KjopsvilkarRoute
  '/moving-inventory-list': typeof MovingInventoryListRoute
  '/nl': typeof NlRoute
  '/no': typeof NoRoute
  '/om-oss': typeof OmOssRoute
  '/personvern': typeof PersonvernRoute
  '/pl': typeof PlRoute
  '/pricing': typeof PricingRoute
  '/pt': typeof PtRoute
  '/se': typeof SeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/vilkar': typeof VilkarRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/en/moving-van-calculator': typeof EnMovingVanCalculatorRoute
  '/estimate/$id': typeof EstimateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/databehandling'
    | '/de'
    | '/demo'
    | '/dk'
    | '/es'
    | '/fi'
    | '/flyttebil-kalkulator'
    | '/fr'
    | '/hjelp'
    | '/it'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/nl'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pl'
    | '/pricing'
    | '/pt'
    | '/se'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/databehandling'
    | '/de'
    | '/demo'
    | '/dk'
    | '/es'
    | '/fi'
    | '/flyttebil-kalkulator'
    | '/fr'
    | '/hjelp'
    | '/it'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/nl'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pl'
    | '/pricing'
    | '/pt'
    | '/se'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/databehandling'
    | '/de'
    | '/demo'
    | '/dk'
    | '/es'
    | '/fi'
    | '/flyttebil-kalkulator'
    | '/fr'
    | '/hjelp'
    | '/it'
    | '/kjopsvilkar'
    | '/moving-inventory-list'
    | '/nl'
    | '/no'
    | '/om-oss'
    | '/personvern'
    | '/pl'
    | '/pricing'
    | '/pt'
    | '/se'
    | '/sitemap.xml'
    | '/upload'
    | '/vilkar'
    | '/checkout/return'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/en/moving-van-calculator'
    | '/estimate/$id'
    | '/dashboard/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DatabehandlingRoute: typeof DatabehandlingRoute
  DeRoute: typeof DeRoute
  DemoRoute: typeof DemoRoute
  DkRoute: typeof DkRoute
  EsRoute: typeof EsRoute
  FiRoute: typeof FiRoute
  FlyttebilKalkulatorRoute: typeof FlyttebilKalkulatorRoute
  FrRoute: typeof FrRoute
  HjelpRoute: typeof HjelpRoute
  ItRoute: typeof ItRoute
  KjopsvilkarRoute: typeof KjopsvilkarRoute
  MovingInventoryListRoute: typeof MovingInventoryListRoute
  NlRoute: typeof NlRoute
  NoRoute: typeof NoRoute
  OmOssRoute: typeof OmOssRoute
  PersonvernRoute: typeof PersonvernRoute
  PlRoute: typeof PlRoute
  PricingRoute: typeof PricingRoute
  PtRoute: typeof PtRoute
  SeRoute: typeof SeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
  VilkarRoute: typeof VilkarRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EnMovingVanCalculatorRoute: typeof EnMovingVanCalculatorRoute
  EstimateIdRoute: typeof EstimateIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databehandling': {
      id: '/databehandling'
      path: '/databehandling'
      fullPath: '/databehandling'
      preLoaderRoute: typeof DatabehandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dk': {
      id: '/dk'
      path: '/dk'
      fullPath: '/dk'
      preLoaderRoute: typeof DkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fi': {
      id: '/fi'
      path: '/fi'
      fullPath: '/fi'
      preLoaderRoute: typeof FiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyttebil-kalkulator': {
      id: '/flyttebil-kalkulator'
      path: '/flyttebil-kalkulator'
      fullPath: '/flyttebil-kalkulator'
      preLoaderRoute: typeof FlyttebilKalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hjelp': {
      id: '/hjelp'
      path: '/hjelp'
      fullPath: '/hjelp'
      preLoaderRoute: typeof HjelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kjopsvilkar': {
      id: '/kjopsvilkar'
      path: '/kjopsvilkar'
      fullPath: '/kjopsvilkar'
      preLoaderRoute: typeof KjopsvilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-inventory-list': {
      id: '/moving-inventory-list'
      path: '/moving-inventory-list'
      fullPath: '/moving-inventory-list'
      preLoaderRoute: typeof MovingInventoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl': {
      id: '/nl'
      path: '/nl'
      fullPath: '/nl'
      preLoaderRoute: typeof NlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no': {
      id: '/no'
      path: '/no'
      fullPath: '/no'
      preLoaderRoute: typeof NoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl': {
      id: '/pl'
      path: '/pl'
      fullPath: '/pl'
      preLoaderRoute: typeof PlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se': {
      id: '/se'
      path: '/se'
      fullPath: '/se'
      preLoaderRoute: typeof SeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/en/moving-van-calculator': {
      id: '/en/moving-van-calculator'
      path: '/en/moving-van-calculator'
      fullPath: '/en/moving-van-calculator'
      preLoaderRoute: typeof EnMovingVanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$id': {
      id: '/estimate/$id'
      path: '/estimate/$id'
      fullPath: '/estimate/$id'
      preLoaderRoute: typeof EstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DatabehandlingRoute: DatabehandlingRoute,
  DeRoute: DeRoute,
  DemoRoute: DemoRoute,
  DkRoute: DkRoute,
  EsRoute: EsRoute,
  FiRoute: FiRoute,
  FlyttebilKalkulatorRoute: FlyttebilKalkulatorRoute,
  FrRoute: FrRoute,
  HjelpRoute: HjelpRoute,
  ItRoute: ItRoute,
  KjopsvilkarRoute: KjopsvilkarRoute,
  MovingInventoryListRoute: MovingInventoryListRoute,
  NlRoute: NlRoute,
  NoRoute: NoRoute,
  OmOssRoute: OmOssRoute,
  PersonvernRoute: PersonvernRoute,
  PlRoute: PlRoute,
  PricingRoute: PricingRoute,
  PtRoute: PtRoute,
  SeRoute: SeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
  VilkarRoute: VilkarRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EnMovingVanCalculatorRoute: EnMovingVanCalculatorRoute,
  EstimateIdRoute: EstimateIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
